# Goldstone Docker Compose Configuration
# Copyright 2015 Solinea, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Goldstone Server Container
gsappdev:
  build: ./docker/Dockerfiles/goldstone-app
  env_file: ./docker/config/goldstone-dev.env
  volumes:
    - .:/home/app
    - ./docker/config/goldstone-app:/home/app/config
  ports:
    - "8000:8000"
  links:
    - gsdb
    - gssearch
    - gstaskq

# Database Container
gsdb:
  build: ./docker/Dockerfiles/goldstone-db
  env_file: ./docker/config/goldstone-dev.env
  volumes_from:
    - gsdbdvc
  ports:
    - "5432:5432"

# Database Data Volume Container
gsdbdvc:
  build: ./docker/Dockerfiles/goldstone-db-dvc
  volumes:
    - /var/lib/postgresql/data

# Logstash Container
gslog:
  build: ./docker/Dockerfiles/goldstone-log
  command: logstash -f /logstash/conf.d -w 1
  volumes:
    - ./docker/config/goldstone-log/conf.d:/logstash/conf.d
    - ./docker/config/goldstone-log/patterns:/opt/logstash/patterns
  ports:
    - "5514:5514"
    - "5515:5515"
    - "5516:5516"
  links:
    - gssearch

# Elasticsearch Container
gssearch:
  build: ./docker/Dockerfiles/goldstone-search
  volumes:
    - ./docker/config/goldstone-search:/usr/share/elasticsearch/config
  ports:
    - "9200:9200"
    - "9300:9300"

# Celery Task Queue Container
gstaskq:
 build: ./docker/Dockerfiles/goldstone-task-queue
 ports:
    - "6379:6379"

# Kibana
gskibana:
  image: kibana:4
  ports:
    - "5601:5601"
  links:
    - "gssearch:elasticsearch"
